### ISSUE TITLE
idea, radius upgrades

### ISSUE THREAD

**Issue by TweekinDragon** [MrDj200/Attractor#5]
i see that you have slated a GUI, one thing i would like to see is better radius the 8x8 x8 is too small, i have a dark mansion and i would like to put this in a room to farm mobs (i suck at mob farms).

also a cheaper version, bout had a heart attack when i saw the recipe. could be nerfed to only work on single mobs, with posible upgrade slots to atract more than the one. 

thanks for the mod

**Comment by MrDj200** [comment]
> one thing i would like to see is better radius the 8x8 x8 is too small

You can configure the Range in the cfg.

> also a cheaper version, bout had a heart attack when i saw the recipe.

Sry for that :D, but the recipe is meant to do that. It can attract the ender Dragon, and my testers told me to make it expensive.

**Comment by TweekinDragon** [comment]
oh i see it now i was looking for attractor not djsmods 

i can see making it expensive for attracting the dragon. but as an alternative make a cheaper one that attracts just zombies or skeletons. there is a block like this in the ender I/O mod that does the same thing but i dont think works on the dragon. the problem is that its probably gona be awhile befor ender IO will be updated to 1.12 

some thing i just found dont know if its a bug tho.
 # Enable or disable if the block is destructible by mobs [default: false]
    B:"Can be mob griefed"=false
this line means that creeper explosions shouldnt break it right? cuz they have broke 2 in my test world from being shot by a skeleton

**Comment by MrDj200** [comment]
> this line means that creeper explosions shouldnt break it right? cuz they have broke 2 in my test world from being shot by a skeleton

Yep. just confirmed it. Working on it now

**Comment by MrDj200** [comment]
fixed it in c895074 .
Waiting for curse to publish now.

**Comment by MrDj200** [comment]
Okay, done (that was unusually quick for curse standards...).
New Version disables destruction by creeper now.

https://minecraft.curseforge.com/projects/attractor/files/2492557
